# Generated by Django 4.1.1 on 2022-11-01 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0005_remove_patientprofile_birthday_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodLipid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.FloatField(blank=True, default=0, verbose_name='总胆固醇(TC)')),
                ('HDL_C', models.FloatField(blank=True, default=0, verbose_name='高密度脂蛋白胆固醇(HDL-C)')),
                ('LDL_C', models.FloatField(blank=True, default=0, verbose_name='低密度脂蛋白胆固醇(LDL-C)')),
                ('LDL_4321', models.FloatField(blank=True, default=0, verbose_name='低密度脂蛋白亚型4+3+2+1胆固醇(LDL4+3+2+1)')),
                ('non_HDL', models.FloatField(blank=True, default=0, verbose_name='非高密度脂蛋白胆固醇(non_HDL)')),
                ('IDL', models.FloatField(blank=True, default=0, verbose_name='中间密度脂蛋白胆固醇')),
                ('VLDL', models.FloatField(blank=True, default=0, verbose_name='极低密度脂蛋白胆固醇')),
                ('HDL2', models.FloatField(blank=True, default=0, verbose_name='高密度脂蛋白2')),
                ('HDL3', models.FloatField(blank=True, default=0, verbose_name='高密度脂蛋白3')),
                ('RLP_C', models.FloatField(blank=True, default=0, verbose_name='残粒样脂蛋白胆固醇')),
                ('VLDL3', models.FloatField(blank=True, default=0, verbose_name='极低密度脂蛋白3')),
                ('sdLDL_C', models.FloatField(blank=True, default=0, verbose_name='小而密低密度脂蛋白胆固醇')),
                ('LDL_type', models.CharField(choices=[('A', 'A型'), ('B', 'B型'), ('A\\B', 'A\\B型')], default='', max_length=20, verbose_name='低密度脂蛋白类型（定性检测，A型，B型，A\\B型）')),
                ('LDL_P', models.FloatField(blank=True, default=0, verbose_name='低密度脂蛋白颗粒')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blood_patient', to='patient.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '血脂亚组分病例数据',
                'verbose_name_plural': '血脂亚组分病例数据',
                'db_table': 'blood_lipid',
            },
        ),
    ]
