# Generated by Django 4.1.1 on 2022-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_lipid_subfraction', '0003_alter_bloodlipid_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodlipid',
            name='HDL2',
            field=models.FloatField(blank=True, null=True, verbose_name='高密度脂蛋白2'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='HDL3',
            field=models.FloatField(blank=True, null=True, verbose_name='高密度脂蛋白3'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='HDL_C',
            field=models.FloatField(blank=True, null=True, verbose_name='高密度脂蛋白胆固醇(HDL-C)'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='IDL',
            field=models.FloatField(blank=True, null=True, verbose_name='中间密度脂蛋白胆固醇'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='LDL_4321',
            field=models.FloatField(blank=True, null=True, verbose_name='低密度脂蛋白亚型4+3+2+1胆固醇(LDL4+3+2+1)'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='LDL_C',
            field=models.FloatField(blank=True, null=True, verbose_name='低密度脂蛋白胆固醇(LDL-C)'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='LDL_P',
            field=models.FloatField(blank=True, null=True, verbose_name='低密度脂蛋白颗粒'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='LDL_type',
            field=models.CharField(choices=[('A', 'A型'), ('B', 'B型'), ('A\\B', 'A\\B型')], max_length=20, null=True, verbose_name='低密度脂蛋白类型（定性检测，A型，B型，A\\B型）'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='RLP_C',
            field=models.FloatField(blank=True, null=True, verbose_name='残粒样脂蛋白胆固醇'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='VLDL',
            field=models.FloatField(blank=True, null=True, verbose_name='极低密度脂蛋白胆固醇'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='VLDL3',
            field=models.FloatField(blank=True, null=True, verbose_name='极低密度脂蛋白3'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='non_HDL',
            field=models.FloatField(blank=True, null=True, verbose_name='非高密度脂蛋白胆固醇(non_HDL)'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='sdLDL_C',
            field=models.FloatField(blank=True, null=True, verbose_name='小而密低密度脂蛋白胆固醇'),
        ),
        migrations.AlterField(
            model_name='bloodlipid',
            name='tc',
            field=models.FloatField(blank=True, null=True, verbose_name='总胆固醇(TC)'),
        ),
    ]
