# Generated by Django 4.1.1 on 2022-12-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blood_lipid_subfraction",
            "0006_bloodlipid_lipid_lipoprotein_barcode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodlipid",
            name="conclusion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ASCVD诊断结论"
            ),
        ),
    ]
