# Generated by Django 4.1.1 on 2022-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascvd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascvdtesting',
            name='ascvd_history',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ASCVD病史'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='chronic_illness',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='慢性病史'),
        ),
    ]
