# Generated by Django 4.1.1 on 2022-11-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patientprofile_birthday_patientprofile_age_and_more'),
        ('ascvd', '0004_ascvdtesting_apo_a1_ascvdtesting_apo_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascvdtesting',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ascvd_patient', to='patient.patientprofile', verbose_name='患者'),
        ),
    ]
