# Generated by Django 4.1.1 on 2022-11-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patientprofile_bmi_patientprofile_application_items_and_more'),
        ('ascvd', '0005_alter_ascvdtesting_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascvdtesting',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ascvd_patient', to='patient.patientprofile', verbose_name='患者'),
        ),
    ]
