# Generated by Django 4.1.1 on 2022-11-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_patientprofile_id'),
        ('ascvd', '0006_alter_ascvdtesting_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascvdtesting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ascvd_patient', to='patient.patientprofile', verbose_name='患者'),
        ),
    ]
