# Generated by Django 4.1.1 on 2022-12-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ascvd", "0008_alter_ascvdtesting_apo_a1_alter_ascvdtesting_apo_b_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="ascvdtesting", name="ascvd_history",),
        migrations.RemoveField(model_name="ascvdtesting", name="chronic_illness",),
    ]
