# Generated by Django 4.1.1 on 2022-12-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ascvd", "0009_remove_ascvdtesting_ascvd_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ascvdtesting",
            name="Lp_barcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="脂蛋白条码号"
            ),
        ),
        migrations.AddField(
            model_name="ascvdtesting",
            name="Lp_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="脂蛋白样本号"
            ),
        ),
        migrations.AddField(
            model_name="ascvdtesting",
            name="Lp_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="脂蛋白样本状态"
            ),
        ),
        migrations.AddField(
            model_name="ascvdtesting",
            name="Lp_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="脂蛋白样本类型"
            ),
        ),
        migrations.AddField(
            model_name="ascvdtesting",
            name="lipids_barcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂条码号"
            ),
        ),
        migrations.AddField(
            model_name="ascvdtesting",
            name="lipids_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂样本号"
            ),
        ),
        migrations.AddField(
            model_name="ascvdtesting",
            name="lipids_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂样本状态"
            ),
        ),
        migrations.AddField(
            model_name="ascvdtesting",
            name="lipids_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂样本类型"
            ),
        ),
    ]
