# Generated by Django 4.1.1 on 2022-09-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patientprofile_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hobby',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='嗜好'),
        ),
    ]
