# Generated by Django 4.1.1 on 2022-11-03 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patientprofile_birthday_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, verbose_name='患者编号'),
        ),
    ]
