# Generated by Django 4.1.1 on 2022-11-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientprofile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='BMI',
            field=models.FloatField(blank=True, null=True, verbose_name='BMI'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='application_items',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='申请项目'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='血压'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='clinical_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='临床诊断'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='科室'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='inpatient_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='病区'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sampler',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='采样者'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='smoked',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=6, verbose_name='吸烟史'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='submitting_doctor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='送检医师'),
        ),
    ]
