# Generated by Django 4.1.1 on 2022-12-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0008_alter_patientprofile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="ascvd_history",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ASCVD病史"
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="chronic_illness",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="慢性病史"
            ),
        ),
    ]
