# Generated by Django 4.1.1 on 2022-11-23 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ascvd", "0008_alter_ascvdtesting_apo_a1_alter_ascvdtesting_apo_b_and_more"),
        (
            "blood_lipid_subfraction",
            "0004_alter_bloodlipid_hdl2_alter_bloodlipid_hdl3_and_more",
        ),
        ("gene_polymorphism", "0003_alter_genepolymorphism_patient"),
        ("patient", "0008_alter_patientprofile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                (
                    "Acq_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="采集时间"
                    ),
                ),
                (
                    "Rec_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="接收时间"
                    ),
                ),
                (
                    "Rep_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="报告时间"
                    ),
                ),
                (
                    "doctor_test",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="检验者"
                    ),
                ),
                (
                    "doctor_exam",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="报告(审核)者"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="XXXX",
                        max_length=100,
                        null=True,
                        verbose_name="医院地址",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "ascvd",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ascvd.ascvdtesting",
                    ),
                ),
                (
                    "blood",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blood_lipid_subfraction.bloodlipid",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gene_polymorphism.genepolymorphism",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="report_patient",
                        to="patient.patientprofile",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告信息",
                "verbose_name_plural": "报告信息",
                "db_table": "report_information",
            },
        ),
    ]
