# Generated by Django 4.1.1 on 2022-09-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorprofile',
            table='doctor_profile',
        ),
    ]
