// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {context} from '../models';

export function CloseWindow():Promise<void>;

export function GetAIStatsWidgetState():Promise<desktop.AIStatsWidgetState>;

export function GetConfigSummary():Promise<desktop.DesktopConfigSummary>;

export function GetDesktopStatus():Promise<desktop.DesktopStatus>;

export function GetRuntimeSummary():Promise<desktop.DesktopRuntimeSummary>;

export function GetVersion():Promise<string>;

export function GetWindowState():Promise<desktop.DesktopWindowState>;

export function HideAIStatsWidget():Promise<desktop.AIStatsWidgetState>;

export function HideToTray():Promise<void>;

export function IsQuitting():Promise<boolean>;

export function MinimiseWindow():Promise<void>;

export function OpenAdminInBrowser():Promise<void>;

export function RestoreLastRoute():Promise<string>;

export function RunSelfCheck():Promise<desktop.DesktopSelfCheck>;

export function SaveWindowState(arg1:desktop.DesktopWindowState):Promise<desktop.DesktopWindowState>;

export function SendNativeNotice(arg1:string,arg2:string):Promise<void>;

export function ShowAIStatsWidget():Promise<desktop.AIStatsWidgetState>;

export function ShowMainWindow():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleAIStatsWidget():Promise<desktop.AIStatsWidgetState>;

export function ToggleMaximiseWindow():Promise<void>;
