# Generated by Django 4.1.1 on 2022-11-01 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0005_remove_patientprofile_birthday_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenePolymorphism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApoE', models.CharField(choices=[('E2/E2', 'E2/E2'), ('E2/E3', 'E2/E3'), ('E3/E3', 'E3/E3'), ('E2/E4', 'E2/E4'), ('E3/E4', 'E3/E4'), ('E4/E4', 'E4/E4')], default='', help_text='ApoE 基因型', max_length=20, verbose_name='ApoE 基因型')),
                ('SLCO1B1', models.CharField(choices=[('*1a/*1a', '*1a/*1a'), ('*1a/*1b', '*1a/*1b'), ('*1b/*1b', '*1b/*1b'), ('*1a/*5', '*1a/*5'), ('*1a/*15', '*1a/*15'), ('*1b/*15', '*1b/*15'), ('*5/*5', '*5/*5'), ('*5/*15', '*5/*15'), ('*15/*15', '*15/*15')], default='', help_text='SLCO1B1基因型', max_length=20, verbose_name='SLCO1B1基因型')),
                ('CYP2C19', models.CharField(choices=[('*2/*2', '*2/*2'), ('*2/*3', '*2/*3'), ('*3/*3', '*3/*3'), ('*1/*2', '*1/*2'), ('*1/*3', '*1/*3'), ('*2/*17', '*2/*17'), ('*3/*17', '*3/*17'), ('*1/*1', '*1/*1'), ('*1/*17', '*1/*17'), ('*17/*17', '*17/*17')], default='', help_text='CYP2C19基因分型', max_length=20, verbose_name='CYP2C19基因分型')),
                ('SLCO1B1_1b_388A', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='SLCO1B1*1b 388A', max_length=10, verbose_name='SLCO1B1*1b 388A')),
                ('SLCO1B1_1b_388G', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='SLCO1B1*1b 388G', max_length=10, verbose_name='SLCO1B1*1b 388G')),
                ('SLCO1B1_5_521T', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='SLCO1B1*5 521T', max_length=10, verbose_name='SLCO1B1*5 521T')),
                ('SLCO1B1_5_521C', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='SLCO1B1*5 521T', max_length=10, verbose_name='SLCO1B1*5 521T')),
                ('ApoE2_526C', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='ApoE2 526C', max_length=10, verbose_name='ApoE2 526C')),
                ('ApoE2_526T', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='ApoE2 526T', max_length=10, verbose_name='ApoE2 526T')),
                ('ApoE4_388T', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='ApoE4 388T', max_length=10, verbose_name='ApoE4 388T')),
                ('ApoE4_388C', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='ApoE4 388C', max_length=10, verbose_name='ApoE4 388C')),
                ('CYP2C19_681_2G', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='CYP2C19-681/*2G', max_length=10, verbose_name='CYP2C19-681/*2G')),
                ('CYP2C19_681_2A', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='CYP2C19-681/*2A', max_length=10, verbose_name='CYP2C19-681/*2A')),
                ('CYP2C19_636_3G', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='CYP2C19-636/*3G', max_length=10, verbose_name='CYP2C19-636/*3G')),
                ('CYP2C19_636_3A', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='CYP2C19-636/*3A', max_length=10, verbose_name='CYP2C19-636/*3A')),
                ('CYP2C19_806_17C', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='CYP2C19-806/*17C', max_length=10, verbose_name='CYP2C19-806/*17C')),
                ('CYP2C19_806_17T', models.CharField(choices=[('阳性(+)', '阳性(+)'), ('阴性', '阴性')], default='', help_text='CYP2C19-806/*17T', max_length=10, verbose_name='CYP2C19-806/*17T')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gene_patient', to='patient.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '基因多态性',
                'verbose_name_plural': '基因多态性',
                'db_table': 'gene_polymorphism',
            },
        ),
    ]
