# Generated by Django 4.1.1 on 2022-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='疾病关键词')),
                ('disease', models.CharField(blank=True, max_length=20, null=True, verbose_name='疾病')),
                ('type_zh', models.CharField(blank=True, max_length=40, null=True, verbose_name='疾病关键词中文')),
            ],
            options={
                'verbose_name': '疾病字典',
                'verbose_name_plural': '疾病字典',
                'db_table': 'disease_dict',
            },
        ),
    ]
