# Generated by Django 4.1.1 on 2022-09-16 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_alter_patientprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AscvdTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.FloatField(blank=True, verbose_name='总胆固醇(TC)')),
                ('tg', models.FloatField(blank=True, verbose_name='甘油三酯(TG)')),
                ('HDL_C', models.FloatField(blank=True, verbose_name='高密度脂蛋白胆固醇(HDL-C)')),
                ('LDL_C', models.FloatField(blank=True, verbose_name='低密度脂蛋白胆固醇(LDL-C)')),
                ('chronic_illness', models.CharField(blank=True, choices=[('高血压', '高血压'), ('糖尿病', '糖尿病')], max_length=40, null=True, verbose_name='慢性病史')),
                ('ascvd_history', models.CharField(blank=True, choices=[('急性冠状动脉综合症', '急性冠状动脉综合症'), ('稳定性冠心病', '稳定性冠心病'), ('血运重建术后', '血运重建术后'), ('缺血性心肌病', '缺血性心肌病'), ('缺血性卒中', '缺血性卒中'), ('短暂性脑缺血发作', '短暂性脑缺血发作'), ('外周动脉粥样硬化病', '外周动脉粥样硬化病'), ('其他疾病', '其他疾病')], max_length=255, null=True, verbose_name='ASCVD病史')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('conclusion', models.CharField(blank=True, max_length=255, null=True, verbose_name='ASCVD诊断结论')),
                ('conclusion_img', models.ImageField(blank=True, help_text='诊断图片', max_length=200, upload_to='conclusion_img/', verbose_name='诊断图片')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='patient.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': 'ascvd病例数据',
                'verbose_name_plural': 'ascvd病例数据',
                'db_table': 'ascvd_testing',
            },
        ),
    ]
