# Generated by Django 4.1.1 on 2022-09-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascvd', '0002_alter_ascvdtesting_ascvd_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascvdtesting',
            name='chronic_illness',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='慢性病史'),
        ),
    ]
