# Generated by Django 4.1.1 on 2022-10-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascvd', '0003_alter_ascvdtesting_chronic_illness'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascvdtesting',
            name='Apo_A1',
            field=models.FloatField(blank=True, default=0, verbose_name='载脂蛋白 A1(Apo_A1)'),
        ),
        migrations.AddField(
            model_name='ascvdtesting',
            name='Apo_B',
            field=models.FloatField(blank=True, default=0, verbose_name='载脂蛋白 B(Apo_B)'),
        ),
        migrations.AddField(
            model_name='ascvdtesting',
            name='LP_a',
            field=models.FloatField(blank=True, default=0, verbose_name='脂蛋白 a(LP_a)'),
        ),
        migrations.AddField(
            model_name='ascvdtesting',
            name='non_HDL',
            field=models.FloatField(blank=True, default=0, verbose_name='非高密度脂蛋白胆固醇(non_HDL)'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='HDL_C',
            field=models.FloatField(blank=True, default=0, verbose_name='高密度脂蛋白胆固醇(HDL-C)'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='LDL_C',
            field=models.FloatField(blank=True, default=0, verbose_name='低密度脂蛋白胆固醇(LDL-C)'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='tc',
            field=models.FloatField(blank=True, default=0, verbose_name='总胆固醇(TC)'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='tg',
            field=models.FloatField(blank=True, default=0, verbose_name='甘油三酯(TG)'),
        ),
    ]
