# Generated by Django 4.1.1 on 2022-11-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascvd', '0007_alter_ascvdtesting_id_alter_ascvdtesting_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascvdtesting',
            name='Apo_A1',
            field=models.FloatField(blank=True, null=True, verbose_name='载脂蛋白 A1(Apo_A1)'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='Apo_B',
            field=models.FloatField(blank=True, null=True, verbose_name='载脂蛋白 B(Apo_B)'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='LP_a',
            field=models.FloatField(blank=True, null=True, verbose_name='脂蛋白 a(LP_a)'),
        ),
        migrations.AlterField(
            model_name='ascvdtesting',
            name='non_HDL',
            field=models.FloatField(blank=True, null=True, verbose_name='非高密度脂蛋白胆固醇(non_HDL)'),
        ),
    ]
