# Generated by Django 4.1.1 on 2022-11-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedict',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
