import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import { REDIRECTS } from './redirects.mjs';
import { rehypeBaseLinks } from './plugins/rehype-base-links.mjs';

// The site is deployed to GitHub Pages under a repository sub-path.
// `actions/configure-pages` exposes the value via the PAGES_BASE_PATH env var
// (the workflow bridges `steps.pages.outputs.base_path` into it), so the same
// build works locally (empty base) and in CI (/archiving-project).
const base = process.env.PAGES_BASE_PATH || '';

// A base that is not an absolute POSIX path means the value was mangled before
// it reached Node — on Windows, Git Bash rewrites any env var that looks like a
// path unless MSYS_NO_PATHCONV=1 is set, silently turning `/archiving-project`
// into `C:/.../PortableGit/.../archiving-project`. Every link on the site would
// then point outside the deployment. Fail loudly instead of shipping that.
if (base && !base.startsWith('/')) {
  throw new Error(
    `PAGES_BASE_PATH must be an absolute path such as "/archiving-project", ` +
      `but got "${base}". On Windows/Git Bash, prefix the build with ` +
      `MSYS_NO_PATHCONV=1 to stop the shell rewriting it.`
  );
}

/**
 * Astro does *not* prepend `base` to a redirect destination, but it does serve
 * the redirect stub from inside the base directory. Left as-is, every legacy
 * URL would bounce the reader to a path outside the repository sub-path and
 * 404. Prefixing here keeps the table in redirects.mjs base-independent.
 */
const redirects = Object.fromEntries(
  Object.entries(REDIRECTS).map(([from, to]) => [
    from,
    base && to.startsWith('/') ? `${base}${to}` : to,
  ])
);

export default defineConfig({
  site: 'https://wychmod.github.io',
  base,
  trailingSlash: 'always',
  // Every URL the retired Jekyll site published. Generated by
  // scripts/gen-redirects.py and frozen — see redirects.mjs for provenance.
  // Astro emits a meta-refresh stub per entry, so no inbound link 404s.
  redirects,
  build: {
    format: 'directory',
    inlineStylesheets: 'auto',
  },
  compressHTML: true,
  // Article bodies keep portable, base-free internal links; the base is applied
  // once here instead of being baked into every Markdown file.
  markdown: {
    rehypePlugins: [[rehypeBaseLinks, { base }]],
  },
  prefetch: {
    prefetchAll: false,
    defaultStrategy: 'hover',
  },
  integrations: [
    sitemap({
      i18n: {
        defaultLocale: 'zh-CN',
        locales: {
          'zh-CN': 'zh-CN',
          en: 'en',
        },
      },
      serialize(item) {
        // Keep the two locale variants in one sitemap with hreflang hints.
        item.changefreq = 'monthly';
        item.priority = item.url.includes('/en/') ? 0.6 : 0.8;
        return item;
      },
    }),
  ],
});
