/**
 * Legacy URL redirect table — GENERATED, do not edit by hand.
 *
 * The previous site was Jekyll + jekyll-theme-chirpy. The rebuild moved
 * posts to /projects/<ref>/ and collapsed the blog-era index pages into
 * the project index. Every URL the old site published is listed here so
 * that no inbound link 404s after the cutover.
 *
 * 24 posts · 8 category archives · 53 tag archives · 3 paginated pages
 * Regenerate with: python scripts/gen-redirects.py
 */
export const REDIRECTS = {
  '/archives/': '/timeline/',
  '/categories/': '/projects/',
  '/categories/ai-llm-应用/': '/projects/?category=ai-llm',
  '/categories/ai-llm/': '/projects/?category=ai-llm',
  '/categories/enterprise-architecture/': '/projects/?category=enterprise',
  '/categories/full-stack-practice/': '/projects/?category=fullstack',
  '/categories/tools-verticals/': '/projects/?category=tools',
  '/categories/企业级-中台架构/': '/projects/?category=enterprise',
  '/categories/全栈练手/': '/projects/?category=fullstack',
  '/categories/工具-垂直领域系统/': '/projects/?category=tools',
  '/page2/': '/projects/',
  '/page3/': '/projects/',
  '/posts/1802axf-en/': '/en/projects/1802axf/',
  '/posts/1802axf-zh/': '/projects/1802axf/',
  '/posts/ascvd-en/': '/en/projects/ascvd/',
  '/posts/ascvd-zh/': '/projects/ascvd/',
  '/posts/bolg-en/': '/en/projects/bolg/',
  '/posts/bolg-zh/': '/projects/bolg/',
  '/posts/chatgpt-next-web-en/': '/en/projects/ChatGPT-Next-Web/',
  '/posts/chatgpt-next-web-zh/': '/projects/ChatGPT-Next-Web/',
  '/posts/cloud-short-link-en/': '/en/projects/cloud-short-link/',
  '/posts/cloud-short-link-zh/': '/projects/cloud-short-link/',
  '/posts/db-router-springboot-starter-en/': '/en/projects/db-router-springboot-starter/',
  '/posts/db-router-springboot-starter-zh/': '/projects/db-router-springboot-starter/',
  '/posts/escontentgen-en/': '/en/projects/ESContentGen/',
  '/posts/escontentgen-zh/': '/projects/ESContentGen/',
  '/posts/huawei-alarm-en/': '/en/projects/huawei-alarm/',
  '/posts/huawei-alarm-zh/': '/projects/huawei-alarm/',
  '/posts/lottery-en/': '/en/projects/lottery/',
  '/posts/lottery-zh/': '/projects/lottery/',
  '/posts/todolist-en/': '/en/projects/ToDoList/',
  '/posts/todolist-zh/': '/projects/ToDoList/',
  '/posts/tokenbridge-en/': '/en/projects/TokenBridge/',
  '/posts/tokenbridge-zh/': '/projects/TokenBridge/',
  '/posts/wiki-en/': '/en/projects/wiki/',
  '/posts/wiki-zh/': '/projects/wiki/',
  '/sitemap.xml': '/sitemap-index.xml',
  '/tags/': '/stack/',
  '/tags/ai-gateway/': '/stack/',
  '/tags/ai-网关/': '/stack/',
  '/tags/aop/': '/stack/',
  '/tags/bootstrap/': '/stack/',
  '/tags/database-sharding/': '/stack/',
  '/tags/ddd/': '/stack/',
  '/tags/desktop-app/': '/stack/',
  '/tags/django/': '/stack/',
  '/tags/drf/': '/stack/',
  '/tags/dubbo/': '/stack/',
  '/tags/electron-builder/': '/stack/',
  '/tags/electron/': '/stack/',
  '/tags/failover/': '/stack/',
  '/tags/fastapi/': '/stack/',
  '/tags/flask/': '/stack/',
  '/tags/go/': '/stack/',
  '/tags/healthcare-it/': '/stack/',
  '/tags/java/': '/stack/',
  '/tags/jinja2/': '/stack/',
  '/tags/jquery/': '/stack/',
  '/tags/lark-openapi/': '/stack/',
  '/tags/microservices/': '/stack/',
  '/tags/mobile-h5/': '/stack/',
  '/tags/mobx/': '/stack/',
  '/tags/mybatis/': '/stack/',
  '/tags/nacos/': '/stack/',
  '/tags/next-js/': '/stack/',
  '/tags/node-js/': '/stack/',
  '/tags/postgresql/': '/stack/',
  '/tags/pwa/': '/stack/',
  '/tags/python/': '/stack/',
  '/tags/react/': '/stack/',
  '/tags/redis/': '/stack/',
  '/tags/sharding-jdbc/': '/stack/',
  '/tags/spring-boot-starter/': '/stack/',
  '/tags/spring-boot/': '/stack/',
  '/tags/spring-cloud-alibaba/': '/stack/',
  '/tags/sqlalchemy/': '/stack/',
  '/tags/sqlite/': '/stack/',
  '/tags/tauri/': '/stack/',
  '/tags/typescript/': '/stack/',
  '/tags/vue-3/': '/stack/',
  '/tags/wails/': '/stack/',
  '/tags/webhook/': '/stack/',
  '/tags/webpack/': '/stack/',
  '/tags/websocket/': '/stack/',
  '/tags/分库分表/': '/stack/',
  '/tags/医疗信息化/': '/stack/',
  '/tags/微服务/': '/stack/',
  '/tags/故障转移/': '/stack/',
  '/tags/桌面应用/': '/stack/',
  '/tags/移动端-h5/': '/stack/',
  '/tags/飞书-openapi/': '/stack/',
};
