# Generated by Django 4.1.1 on 2022-11-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_patientprofile_id'),
        ('gene_polymorphism', '0002_alter_genepolymorphism_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genepolymorphism',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gene_patient', to='patient.patientprofile', verbose_name='患者'),
        ),
    ]
