# Generated by Django 4.1.1 on 2022-12-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene_polymorphism", "0003_alter_genepolymorphism_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="genepolymorphism",
            name="clopidogrel_barcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=" 氯吡格雷条码号"
            ),
        ),
        migrations.AddField(
            model_name="genepolymorphism",
            name="clopidogrel_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=" 氯吡格雷样本号"
            ),
        ),
        migrations.AddField(
            model_name="genepolymorphism",
            name="clopidogrel_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=" 氯吡格雷样本状态"
            ),
        ),
        migrations.AddField(
            model_name="genepolymorphism",
            name="clopidogrel_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=" 氯吡格雷样本类型"
            ),
        ),
        migrations.AddField(
            model_name="genepolymorphism",
            name="statin_barcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="他汀条码号"
            ),
        ),
        migrations.AddField(
            model_name="genepolymorphism",
            name="statin_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="他汀样本号"
            ),
        ),
        migrations.AddField(
            model_name="genepolymorphism",
            name="statin_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="他汀样本状态"
            ),
        ),
        migrations.AddField(
            model_name="genepolymorphism",
            name="statin_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="他汀样本类型"
            ),
        ),
    ]
