# Generated by Django 4.1.1 on 2022-12-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blood_lipid_subfraction",
            "0004_alter_bloodlipid_hdl2_alter_bloodlipid_hdl3_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodlipid",
            name="Apo_A1",
            field=models.FloatField(
                blank=True, null=True, verbose_name="载脂蛋白 A1(Apo_A1)"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="Apo_B",
            field=models.FloatField(
                blank=True, null=True, verbose_name="载脂蛋白 B(Apo_B)"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="LP_a",
            field=models.FloatField(blank=True, null=True, verbose_name="脂蛋白 a(LP_a)"),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="tg",
            field=models.FloatField(blank=True, default=0, verbose_name="甘油三酯(TG)"),
        ),
    ]
