# Generated by Django 4.1.1 on 2022-12-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blood_lipid_subfraction",
            "0005_bloodlipid_apo_a1_bloodlipid_apo_b_bloodlipid_lp_a_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodlipid",
            name="Lipid_lipoprotein_barcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂与脂蛋白条码号"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="Lipid_lipoprotein_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂与脂蛋白样本号"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="Lipid_lipoprotein_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂与脂蛋白样本状态"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="Lipid_lipoprotein_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂与脂蛋白样本类型"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="blood_barcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂亚组分条码号"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="blood_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂亚组分样本号"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="blood_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂亚组分样本状态"
            ),
        ),
        migrations.AddField(
            model_name="bloodlipid",
            name="blood_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="血脂亚组分样本类型"
            ),
        ),
    ]
