# Generated by Django 4.1.1 on 2022-09-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientprofile',
            table='patient_profile',
        ),
    ]
