# Generated by Django 4.1.1 on 2022-09-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_alter_patientprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='医生'),
        ),
    ]
